version: '3'

tasks:
  all:
    cmds:
      - task: cleanup
      - task: build
      - task: package
      - task: adb
    silent: true

  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - mkdir -p build/lib
      - docker buildx build --platform=linux/arm64 -t retro-console-arm64 -f Dockerfile .
    silent: true

  package:
    cmds:
      - docker create --name extract retro-console-arm64
      - docker cp extract:/build/save-sync build/power-menu
      - docker cp extract:/usr/lib/aarch64-linux-gnu/libSDL2_gfx-1.0.so.0.0.2 build/lib/libSDL2_gfx-1.0.so.0
      - rm -rf build/Power.pak || true
      - mkdir -p build/Power.pak
      - mkdir -p build/Power.pak/resources/lib
      - cp build/power-menu launch.sh README.md LICENSE pak.json build/Power.pak
      - cp -R build/lib build/Power.pak/resources
    silent: true

  cleanup:
    cmds:
      - docker rm extract || true
    silent: true

  adb:
    cmds:
      - adb shell rm -rf /mnt/SDCARD/Tools/tg5040/Power.pak || true
      - adb push build/Power.pak /mnt/SDCARD/Tools/tg5040
      - say Finished deploying Power Menu!
    silent: true

